### ISSUE TITLE
hardcoded state: new, should probably be state: no changes

### ISSUE THREAD

**Issue by firecow** [sudo-bmitch/docker-stack-wait#13]
https://github.com/sudo-bmitch/docker-stack-wait/blob/main/docker-stack-wait.sh#L90

I find that this hardcoded "new" state, more often than not means "nothing to update"

Thanks for this great little container, we at Cego A/S use it quiet extensively.

**Comment by firecow** [comment]
https://github.com/sudo-bmitch/docker-stack-wait/pull/14 I've made a pull request :smile: If you agree...

**Comment by sudo-bmitch** [comment]
Naming things is hard. I'm hesitant to go with "no changes" since a deploy of a service for the first time is a use case many will see often in ephemeral CI environments. Something like "new-or-unchanged" or maybe a slightly ambiguous "deployed" would probably be better. There are a few others changes needed for this (in particular moving the builds to GitHub Actions), so I'll have a look at this later this week.

**Comment by firecow** [comment]
Ahh... Sorry, i didn't think that new and no-changes was actually the same "update state"

What about using a combination of docker service ps and docker service inspect, to figure out if its actually "new" or if the service is "unchanged" ?

Would that be possible ?

**Comment by sudo-bmitch** [comment]
I'm not sure of a great way to reliably tell the difference since any deploy that doesn't modify the service won't result in a change to the `.UpdateStatus.State`. If the state exists from a previous deploy, we'd still say `completed` even when it's really unchanged. The timestamps inside the inspect aren't a lot of help since various actions can cause the `UpdatedAt` timestamp to change separate from the `CompletedAt`. For right now, I'm just going to keep it simple and avoid a long list of edge cases I suspect people have, and so I went with `deployed` as the hard coded name.

Hope that helps. Closing for now, but feel free to keep the conversation going or submit a PR if there's a better way I'm missing.
